# Generated by Django 3.0.3 on 2020-10-29 11:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_auto_20201026_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='ID_num',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999999999)]),
        ),
    ]
